version: '3.1'

services:
  #########################
  ## neo4j
  #########################
  korszeru-neo4j:
    image: neo4j:4.1.3
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - korszeru-db-neo4j-data:/data

volumes:
  korszeru-db-neo4j-data:
