version: '3.1'

services:
  #########################
  ## MongoDB
  #########################
  korszeru-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - korszeru-db-mongo-data:/data/configdb

volumes:
  korszeru-db-mongo-data:
